const listadoAnimales = [{
	"id": 1,
	"name": "Fafi",
	"description": "Fafi es un perrito muy lindo y amigable.",
	"picture": "https://i.ibb.co/kJCkwTY/perro-1.jpg",
	"barrio": "Centro, Montevideo",
	"tipo": "Perro",
	"raza": "Mestizo",
	"edad": "2",
	"sexo": "Macho",
	"colorPeloYOjos": "Pelaje rubio, ojos marrones",
	"datosContacto": {"nombre": "Carlos Lopez", "Telefono":"099999999"},
},
{
	"id": 2,
	"name": "Michi",
	"description": "Michi es un gato muy activo",
	"picture": "https://i.ibb.co/1ZXm1ny/gato-3.jpg",
	"barrio": "Barrio sur",
	"tipo": "Gato",
	"raza": "Mestizo",
	"edad": "5",
	"sexo": "Macho",
	"colorPeloYOjos": "Pelaje amarillo, ojos marrones",
	"datosContacto": {"nombre": "Carlos Lopez", "Telefono":"099999999"},
},
{
	"id": 3,
	"name": "Pancho",
	"description": "Pancho es muy tranquilo",
	"picture": "https://i.ibb.co/w0JjfC0/perro-3.jpg",
	"barrio": "Pocitos",
	"tipo": "Perro",
	"raza": "Mestizo",
	"edad": "4",
	"sexo": "Macho",
	"colorPeloYOjos": "Pelaje combinado, ojos marrones",
	"datosContacto": {"nombre": "Carlos Lopez", "Telefono":"099999999"},
},
];

module.exports = listadoAnimales;