const listadoAnimales = [{
	"id": 1,
	"name": "Fafi",
	"description": "Fafi es un perrito muy lindo y amigable.",
	"picture": "https://i.ibb.co/kJCkwTY/perro-1.jpg",
	"barrio": "Centro, Montevideo",
	"tipo": "Perro",
	"raza": "Mestizo",
	"edad": "2",
	"sexo": "Macho",
	"colorPeloYOjos": "Pelaje rubio, ojos marrones",
	"datosContacto": {"nombre": "Carlos Lopez", "Telefono":"099999999"},
},
{
	"id": 2,
	"name": "",
	"description": "",
	"picture": "",
	"barrio": "",
	"tipo": "",
	"raza": "",
	"edad": "",
	"sexo": "",
	"colorPeloYOjos": "",
	"datosContacto": "",
},
{
	"id": 3,
	"name": "",
	"description": "",
	"picture": "",
	"barrio": "",
	"tipo": "",
	"raza": "",
	"edad": "",
	"sexo": "",
	"colorPeloYOjos": "",
	"datosContacto": "",
},
{
	"id": 4,
	"name": "",
	"description": "",
	"picture": "",
	"barrio": "",
	"tipo": "",
	"raza": "",
	"edad": "",
	"sexo": "",
	"colorPeloYOjos": "",
	"datosContacto": "",
},
];

module.exports = listadoAnimales;